services:
  - type: web
    name: Basket-Service
    env: docker
    plan: free
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
