services:
  - type: web
    name: Basket-Service
    env: docker
    plan: free
    healthCheckPath: /
    autoDeploy: true
    dockerCommand: npm start
    dockerContext: .
    dockerfilePath: ./Dockerfile
    buildFilter:
      ignoredPaths: []
    envVars:
      - key: NODE_ENV
        value: production
      - key: DOCKER_BUILDKIT
        value: "1"
