services:
  - type: web
    name: Basket-Service
    env: docker
    plan: free
    healthCheckPath: /
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
